### ISSUE TITLE
Add `./Asset/packageName.meta` to `.gitignore`

### ISSUE THREAD

**Issue by wasabi-neko** [JCxYIS/Lost-Dog#21]
as the title says.
The `{theNameOfPackageName}.meta` in the folder is quite annoying when we use the  commands like `git status` or `git diff .`. (´Ａ｀。)
And the only changes between those `.meta` files is the `uuid` of the folders.

**Comment by JCxYIS** [comment]
`.meta` file in Unity is used to recognize relations between assets, so straightly removing all meta files is not a wish choice.
