### ISSUE TITLE
Player can move character when loading

### ISSUE THREAD

**Issue by wasabi-neko** [JCxYIS/Lost-Dog#7]
I think that player can move the chara when loading is not a good idea...
Maybe we can just ban all of the player operation when loading.

**Comment by JCxYIS** [comment]
Reported. 
Will be fixed soon!
Also, this is not an invalid issue, "invalid" tag should me removed.

**Comment by JCxYIS** [comment]
fixed in commit 7a97849ee8bb527f0b2f6915f5e26a0bb79b0e55

**Comment by JCxYIS** [comment]
fixed in https://github.com/JCxYIS/Lost-Dog/commit/2aa255ecbbbd406085ddd81954fe19eb7090622a
